version: '3'

services:
  reverse-proxy:
    # The official v3 Traefik docker image
    image: traefik:v3.1.2
    restart: always
    mem_limit: 256M
    cpus: 0.2
    # Enables the web UI and tells Traefik to listen to docker
    command: 
      - "--api.insecure=true"
      - "--api.debug=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
#      - "--entryPoints.web.reusePort=true"
      - "--entryPoints.websecure.http.tls.certResolver=myresolver"
#      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesResolvers.myresolver.acme.dnsChallenge=true"
      - "--certificatesResolvers.myresolver.acme.dnsChallenge.provider=cloudflare"
      - "--certificatesResolvers.myresolver.acme.httpChallenge=true"
      - "--metrics.addinternals"
      - "--accesslog=true"
      - "--accesslog.format=json"
      - "--accesslog.fields.headers.defaultmode=keep"
      - "--accesslog.fields.headers.names.User-Agent=keep"
      - "--accesslog.fields.defaultmode=keep"
      - "--log.format=json"
      - "--log.maxbackups=14"
      - "--accesslog.filepath=/var/logs/access.log"
      - "--accesslog.bufferingsize=500"
      - "--metrics.otlp=true"
      - "--metrics.otlp.addEntryPointsLabels=true"
      - "--metrics.otlp.addServicesLabels=true"
      - "--metrics.otlp.pushInterval=30s"
      - "--metrics.otlp.http.endpoint=http://localhost:4318/v1/metrics"
      - "--metrics.otlp.grpc=true"
      - "--metrics.otlp.grpc.endpoint=localhost:4317"
      - "--metrics.otlp.grpc.insecure=true"

      
     #Uncomment for Staging LE Certs
     # - "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=postmaster@saltysysadmin.org"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.myresolver.acme.certificatesDuration=2160"
      - "--certificatesresolvers.myresolver.acme.keytype=RSA4096"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      ## Plugins: 
      - "--experimental.plugins.cloudflarewarp.modulename=github.com/BetterCorp/cloudflarewarp"
      - "--experimental.plugins.cloudflarewarp.version=v1.3.3"
    ports:
      # The HTTP port
      - "80:80"
      # HTTPS port
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - letsencrypt:/letsencrypt
      - traefik_logs:/var/logs
    environment:
      CLOUDFLARE_EMAIL: ${CLOUDFLARE_API_EMAIL}
      CLOUDFLARE_DNS_API_TOKEN: ${CLOUDFLARE_DNS_API_TOKEN}
    networks:
      - proxy
volumes:
  letsencrypt:
    driver: local
  traefik_logs:
    driver: local
networks:
  proxy:
    name: proxy
    driver: bridge
