networks:
  xwiki:
  driver:
  proxy:
    external: true

volumes:
  xwiki-data:
  xwiki-postgres:
  xwiki-postgres-backup:
  xwiki-data-backups:
  xwiki-database-backups:

services:
  postgres:
    image: ${XWIKI_POSTGRES_IMAGE_TAG}
    volumes:
      - xwiki-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${XWIKI_DB_NAME}
      POSTGRES_USER: ${XWIKI_DB_USER}
      POSTGRES_PASSWORD: ${XWIKI_DB_PASSWORD}
    networks:
      - xwiki
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${XWIKI_DB_NAME}", "-U", "${XWIKI_DB_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    restart: unless-stopped

  xwiki:
    image: ${XWIKI_IMAGE_TAG}
    volumes:
      - xwiki-data:${DATA_PATH}
    environment:
      DB_HOST: postgres
      DB_DATABASE: ${XWIKI_DB_NAME}
      DB_USER: ${XWIKI_DB_USER}
      DB_PASSWORD: ${XWIKI_DB_PASSWORD}
    ports:
      - "2080:8080"
    networks:
      - xwiki
      - proxy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    labels:
      - traefik.enable=true
      - traefik.http.routers.xwiki.rule=Host(`${XWIKI_HOSTNAME}`)
      - traefik.docker.network=proxy
      - traefik.http.routers.xwiki.entrypoints=websecure
      - traefik.http.routers.xwiki.tls=true
      - traefik.http.routers.xwiki.tls.certresolver=myresolver
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
  backups:
    image: ${XWIKI_POSTGRES_IMAGE_TAG}
    command: >-
      sh -c 'sleep $BACKUP_INIT_SLEEP &&
      while true; do
        pg_dump -h postgres -p 5432 -d $XWIKI_DB_NAME -U $XWIKI_DB_USER | gzip > $POSTGRES_BACKUPS_PATH/$POSTGRES_BACKUP_NAME-$(date "+%Y-%m-%d_%H-%M").gz &&
        tar -zcpf $DATA_BACKUPS_PATH/$DATA_BACKUP_NAME-$(date "+%Y-%m-%d_%H-%M").tar.gz $DATA_PATH &&
        find $POSTGRES_BACKUPS_PATH -type f -mtime +$POSTGRES_BACKUP_PRUNE_DAYS | xargs rm -f &&
        find $DATA_BACKUPS_PATH -type f -mtime +$DATA_BACKUP_PRUNE_DAYS | xargs rm -f;
        sleep $BACKUP_INTERVAL; done'
    volumes:
      - xwiki-postgres-backup:/var/lib/postgresql/data
      - xwiki-data:${DATA_PATH}
      - xwiki-data-backups:${DATA_BACKUPS_PATH}
      - xwiki-database-backups:${POSTGRES_BACKUPS_PATH}
    environment:
      XWIKI_DB_NAME: ${XWIKI_DB_NAME}
      XWIKI_DB_USER: ${XWIKI_DB_USER}
      PGPASSWORD: ${XWIKI_DB_PASSWORD}
      BACKUP_INIT_SLEEP: ${BACKUP_INIT_SLEEP}
      BACKUP_INTERVAL: ${BACKUP_INTERVAL}
      POSTGRES_BACKUP_PRUNE_DAYS: ${POSTGRES_BACKUP_PRUNE_DAYS}
      DATA_BACKUP_PRUNE_DAYS: ${DATA_BACKUP_PRUNE_DAYS}
      POSTGRES_BACKUPS_PATH: ${POSTGRES_BACKUPS_PATH}
      DATA_BACKUPS_PATH: ${DATA_BACKUPS_PATH}
      DATA_PATH: ${DATA_PATH}
      POSTGRES_BACKUP_NAME: ${POSTGRES_BACKUP_NAME}
      DATA_BACKUP_NAME: ${DATA_BACKUP_NAME}
    networks:
      - xwiki
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
